### ISSUE TITLE
Security vulnerability in jwt-go

### ISSUE THREAD

**Issue by deridiot** [zhaow-de/pam-keycloak-oidc#12]
https://github.com/dgrijalva/jwt-go/issues/428

Furthermore that project is now archived. The new repository is located at https://github.com/golang-jwt/jwt which also addresses the security vulnerability.

```
- github.com/dgrijalva/jwt-go v3.2.0+incompatible
+ github.com/golang-jwt/jwt v3.2.2+incompatible
```

**Comment by varlenthegray** [comment]
For anyone who stumbles upon this, I forked and updated this:

https://github.com/varlenthegray/pam-keycloak-oidc

**Comment by zhaow-de** [comment]
Thanks a lot. The update is released with https://github.com/zhaow-de/pam-keycloak-oidc/releases/tag/r1.2.2
